version: "3.9"

services:
  sample-app:
    build : ./
    image: sample-app
    command: /bin/zsh
    volumes: 
      - ./:/sample-app
    networks:
      - redis_net
      - db_net
    depends_on:
      - redis
      - db

  redis:
    image: redis:6.2.7-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./redis-config/redis.conf:/usr/local/etc/redis/redis.conf
      - ./redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - redis_net

  db:
    image: postgres:14.2-alpine3.15 
    restart: always
    environment:
      POSTGRES_DB: sample_app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: siridog
    volumes:
      - ./db-data:/var/lib/postgresql
      - ./db-backups:/db-backups
      - ./db-backups/sample_app.sql.gz:/docker-entrypoint-initdb.d/sample_app.sql.gz
    ports:
      - "5432:5432"
    networks:
      - db_net

networks:
  redis_net:
  db_net:

volumes:
  redis-data:
  db-data:

