version: "3.9"

x-service: &default-service
    build: ./
    image: django-app
    environment:
      DB_HOST: db
      DB_NAME: fake_project
      DB_USER: root
      DB_PASSWORD: siridog
      DJANGO_SU_NAME: admin
      DJANGO_SU_EMAIL: admin@mail.com
      DJANGO_SU_PASSWORD: secret
    restart: "no"
    env_file:
      - .django_env
    volumes:
      - ./fakeproject:/fakeproject
    networks:
      - db_net
    depends_on:
      - db

services:
  django-server:
    <<: *default-service
    entrypoint: django-admin runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_started
      migrate:
        condition: service_completed_successfully

  django-shell:
    <<: *default-service
    command: django-admin shell

  migrate:
    <<: *default-service
    command: python manage.py migrate

  redis:
    image: redis:6.2.7-alpine
    command: redis-server /usr/local/etc/redis/redis.conf
    volumes:
      - ./containers/redis-config/redis.conf:/usr/local/etc/redis/redis.conf
      - ./containers/redis-data:/data
    ports:
      - "6379:6379"
    networks:
      - redis_net

  db:
    image: postgres:14.2-alpine3.15
    environment:
      POSTGRES_DB: fake_project
      POSTGRES_USER: root
      POSTGRES_PASSWORD: siridog
    volumes:
      - ./containers/db-data:/var/lib/postgresql
    ports:
      - "5431:5432"
    networks:
      - db_net

  node-watch:
    image: node:14.19.1-alpine3.14
    command: npm run watch
    working_dir: /fakeproject
    ports:
      - "7654:7654"
    volumes:
      - ./fakeproject:/fakeproject

networks:
  redis_net:
  db_net:

volumes:
  redis-data:
  db-data:
